Repository exercism/java-analyzer, pull requests merged in 2024-01, with the labels that each got.

#81 Update to Java 21
  Dockerfile
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/analyzer/Statistics.java
Labels: x:size/small

#83 Use Java 21 in GitHub Actions
  .github/workflows/gradle.yml
Labels: x:size/tiny

#82 Refactor analyzer
  .gitattributes
  build.gradle
  src/main/java/analyzer/Analysis.java
  src/main/java/analyzer/Analyzer.java
  src/main/java/analyzer/AnalyzerRoot.java
  src/main/java/analyzer/Comment.java
  src/main/java/analyzer/CommentType.java
  src/main/java/analyzer/Main.java
  src/main/java/analyzer/OutputWriter.java
  src/main/java/analyzer/comments/AvoidHardCodedTestCases.java
  src/main/java/analyzer/comments/ConstructorTooLong.java
  src/main/java/analyzer/comments/MethodTooLong.java
  src/main/java/analyzer/comments/UseProperClassName.java
  src/main/java/analyzer/comments/UseProperMethodName.java
  src/main/java/analyzer/exercises/Comment.java
  src/main/java/analyzer/exercises/Exercise.java
  src/main/java/analyzer/exercises/GeneralComment.java
  src/main/java/analyzer/exercises/Params.java
  src/main/java/analyzer/exercises/hamming/AvoidCharacterLiterals.java
  src/main/java/analyzer/exercises/hamming/CalculateDistanceInConstructor.java
  src/main/java/analyzer/exercises/hamming/Hamming.java
  src/main/java/analyzer/exercises/hamming/HammingAnalyzer.java
  src/main/java/analyzer/exercises/hamming/HammingComment.java
  src/main/java/analyzer/exercises/hamming/MustCalculateHammingDistance.java
  src/main/java/analyzer/exercises/hamming/MustThrowInConstructor.java
  src/main/java/analyzer/exercises/hamming/MustUseConditionalLogicInConstructor.java
  src/main/java/analyzer/exercises/hamming/MustUseConstructor.java
  src/main/java/analyzer/exercises/hamming/MustUseStringCharAtOrCodePointAt.java
  src/main/java/analyzer/exercises/hamming/ShouldUseStreamFilterAndCount.java
  src/main/java/analyzer/exercises/hamming/ShouldUseStringIsEmpty.java
  src/main/java/analyzer/exercises/twofer/AvoidStringFormat.java
  src/main/java/analyzer/exercises/twofer/Twofer.java
  src/main/java/analyzer/exercises/twofer/TwoferAnalyzer.java
  src/main/java/analyzer/exercises/twofer/TwoferComment.java
  src/main/java/analyzer/exercises/twofer/UseConditionalLogic.java
  src/main/java/analyzer/exercises/twofer/UseOneReturn.java
  src/main/java/analyzer/exercises/twofer/UseTernaryOperator.java
  src/test/java/analyzer/ExerciseAnalyzerTest.java
  src/test/java/analyzer/OutputWriterTest.java
  src/test/java/analyzer/exercises/hamming/HammingAnalyzerTest.java
  src/test/java/analyzer/exercises/hamming/HammingTest.java
  src/test/java/analyzer/exercises/twofer/TwoferAnalyzerTest.java
  src/test/java/analyzer/exercises/twofer/TwoferTest.java
  tests/hamming/expected_analysis.json
  tests/unknown-exercise/.meta/config.json
  tests/unknown-exercise/expected_analysis.json
  tests/unknown-exercise/expected_tags.json
  tests/unknown-exercise/src/main/java/UnknownExercise.java
Labels: x:size/large

#95 Removing ``isEmpty()`` comment from hamming analyzer
  gradlew.bat
  src/main/java/analyzer/exercises/hamming/HammingAnalyzer.java
  src/main/java/analyzer/exercises/hamming/HammingWalker.java
  src/main/java/analyzer/exercises/hamming/ShouldUseStringIsEmpty.java
  src/test/java/analyzer/exercises/hamming/HammingAnalyzerTest.java
  src/test/resources/analyzer/exercises/hamming/ShouldUseStringIsEmpty.java.txt
  tests/hamming/expected_analysis.json
Labels: x:size/small
